# Generated by Django 6.1 on 2026-09-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_car_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
    ]
